apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-deploy
  namespace: podinfo
spec:
  interval: 2m0s
  path: ./flux/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo-deploy
  targetNamespace: podinfo
