apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-deploy
  namespace: podinfo
spec:
  interval: 1m0s
  path: ./flux
  prune: false
  serviceAccountName: podinfo
  sourceRef:
    kind: GitRepository
    name: podinfo-deploy